In [56]:
import numpy as np

In [59]:
np.arange(2,10,dtype=np.float32)

array([2., 3., 4., 5., 6., 7., 8., 9.], dtype=float32)

In [60]:
np.linspace(1,10,12,dtype=np.float32)

array([ 1.       ,  1.8181819,  2.6363637,  3.4545455,  4.2727275,
        5.090909 ,  5.909091 ,  6.7272725,  7.5454545,  8.363636 ,
        9.181818 , 10.       ], dtype=float32)

In [67]:
np.eye(4,5,0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [77]:
np.vander([1,2,3,4],3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [75]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [76]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [88]:
class Sunj:
    """
        这是注释信息
    """
    def __init__(self,name):
        """
            初始话
        """
        self.name = name
    def say(self):
        """
            初始话
        """
        print("====")

    @staticmethod
    def is_adult(age):
        """
            staticmethod
        """
        return age >= 18
        
help(Sunj)

Help on class Sunj in module __main__:

class Sunj(builtins.object)
 |  Sunj(name)
 |
 |  这是注释信息
 |
 |  Methods defined here:
 |
 |  __init__(self, name)
 |      初始话
 |
 |  say(self)
 |      初始话
 |
 |  ----------------------------------------------------------------------
 |  Static methods defined here:
 |
 |  is_adult(age)
 |      staticmethod
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables
 |
 |  __weakref__
 |      list of weak references to the object



In [104]:
import types
[method for method in dir(np.random) if isinstance(getattr(np.random,method),types.BuiltinFunctionType) & method.startswith("ran")]

['rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf']

In [98]:
type(np.random.random)

builtin_function_or_method

In [137]:
import numpy as np

x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [141]:
x[-3:3:1]

array([], dtype=int64)

In [148]:
import numpy as np

# 创建一个 3x4x5 的三维数组
arr = np.arange(60).reshape(3, 4, 5)

# 为每个维度创建 slice 对象
slice1 = slice(0, 2)
slice2 = slice(1, 3)
slice3 = slice(2, 4)

# 使用 slice 对象进行切片
sliced_arr = arr[slice1, slice2, slice3]
print("使用 slice 对象切片的结果形状:", sliced_arr.shape,sliced_arr)

使用 slice 对象切片的结果形状: (2, 2, 2) [[[ 7  8]
  [12 13]]

 [[27 28]
  [32 33]]]


In [152]:
arr[:,np.newaxis,:,:].shape

(3, 1, 4, 5)

In [153]:
x = np.arange(5)
x

array([0, 1, 2, 3, 4])

In [168]:
x1 = x[:,np.newaxis]
np.repeat(x1,5,axis=1)

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [157]:
x[np.newaxis,:]

array([[0, 1, 2, 3, 4]])

In [158]:
x[:,np.newaxis] + x[np.newaxis,:]

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [170]:
import numpy as np

# 创建一个一维数组
arr = np.array([1, 2, 3])

# 在第 0 维插入新维度
arr_2d_row = np.expand_dims(arr, axis=0)
print("在第 0 维插入新维度后的形状:", arr_2d_row.shape,arr_2d_row)

# 在第 1 维插入新维度
arr_2d_col = np.expand_dims(arr, axis=1)
print("在第 1 维插入新维度后的形状:", arr_2d_col.shape,arr_2d_row)


在第 0 维插入新维度后的形状: (1, 3) [[1 2 3]]
在第 1 维插入新维度后的形状: (3, 1) [[1 2 3]]


In [171]:
y = np.arange(35).reshape(5, 7)
y
y[np.array([0, 2, 4]), np.array([0, 1, 2])]

array([ 0, 15, 30])

In [177]:
y[np.array([0, 2, 4]),[0, 2, 4]]

array([ 0, 16, 32])

In [182]:
x = np.array([[1., 2.], [np.nan, 3.], [np.nan, np.nan]])
x[~np.isnan(x)]

array([nan, nan, nan])

In [188]:
x = np.array([[0, 1], [1, 1], [2, 2]])
rowsum = x.sum(-1)
rowsum<=2
x[rowsum <=2 ,:]

array([[0, 1],
       [1, 1]])

In [198]:
x = np.array([[ 0,  1,  2],
              [ 3,  4,  5],
              [ 6,  7,  8],
              [ 9, 10, 11]])
rows = (x.sum(-1) % 2) == 0
columns = [0, 2]
np.ix_(rows, columns),rows,x.shape,x[np.ix_(rows, columns)]


((array([[1],
         [3]]),
  array([[0, 2]])),
 array([False,  True, False,  True]),
 (4, 3),
 array([[ 3,  5],
        [ 9, 11]]))

numpy.dtype

In [200]:
np.array(["hello", "world!!!!!"]).dtype

dtype('<U10')

In [204]:
import numpy as np

# 创建一维数组
arr = np.array([[1,2,3],[4,5,6]])

# 使用 flat 属性遍历数组
for element in arr.flat:
    print(element)

1
2
3
4
5
6


In [213]:
# np.iinfo(int) # Bounds of the default integer on this system.
np.iinfo(np.int32) # Bounds of a 32-bit integer
np.iinfo(np.int64) # Bounds of a 64-bit integer

iinfo(min=-9223372036854775808, max=9223372036854775807, dtype=int64)

In [217]:
import numpy as np
a = np.array([[ 0.0,  0.0,  0.0],
              [10.0, 10.0, 10.0],
              [20.0, 20.0, 20.0],
              [30.0, 30.0, 30.0]])

b = np.array([1.0, 2.0, 3.0])
c = a + b
a.shape,b.shape,c.shape,c
# b = np.array([1.0, 2.0, 3.0, 4.0])
# a + b


((4, 3),
 (3,),
 (4, 3),
 array([[ 1.,  2.,  3.],
        [11., 12., 13.],
        [21., 22., 23.],
        [31., 32., 33.]]))

In [222]:
import numpy as np
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
a[:, np.newaxis],a.shape,b.shape


(array([[ 0.],
        [10.],
        [20.],
        [30.]]),
 (4,),
 (3,))

In [223]:
np.array([b"hello", b"world"])

array([b'hello', b'world'], dtype='|S5')

In [228]:
mark = {False: ' -', True: ' Y'}
def print_table(ntypes):
    print('X ' + ' '.join(ntypes))
    for row in ntypes:
        print(row, end='')
        for col in ntypes:
            print(mark[np.can_cast(row, col)], end='')
        print()
np.typecodes['All'],print_table(np.typecodes['All'])

X ? b h i l q p B H I L Q P e f d g F D G S U V O M m
? Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
b - Y Y Y Y Y Y - - - - - - Y Y Y Y Y Y Y Y Y Y Y - Y
h - - Y Y Y Y Y - - - - - - - Y Y Y Y Y Y Y Y Y Y - Y
i - - - Y Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
l - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
q - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
p - - - - Y Y Y - - - - - - - - Y Y - Y Y Y Y Y Y - Y
B - - Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y Y - Y
H - - - Y Y Y Y - Y Y Y Y Y - Y Y Y Y Y Y Y Y Y Y - Y
I - - - - Y Y Y - - Y Y Y Y - - Y Y - Y Y Y Y Y Y - Y
L - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
Q - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
P - - - - - - - - - - Y Y Y - - Y Y - Y Y Y Y Y Y - -
e - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y Y - -
f - - - - - - - - - - - - - - Y Y Y Y Y Y Y Y Y Y - -
d - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
g - - - - - - - - - - - - - - - Y Y - Y Y Y Y Y Y - -
F - - - - - - - - - - - - - 

('?bhilqpBHILQPefdgFDGSUVOMm', None)

In [232]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
buffer_obj = arr.data
buffer_obj,arr.tobytes()

(<memory at 0x10b7dee00>, b'\x01\x00\x00\x00\x02\x00\x00\x00\x03\x00\x00\x00')

In [237]:
import numpy as np

arr = np.array([1, 2, 3], dtype=np.int32)
new_arr = arr.view(dtype=np.int8)
print(new_arr)

[1 0 0 0 2 0 0 0 3 0 0 0]
