In [14]:
import pandas as pd
import numpy as np
index = pd.date_range("2000-01-01", periods=8,freq="MS")

s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])

df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=["A", "B", "C"])

In [15]:
index,s,df

(DatetimeIndex(['2000-01-01', '2000-02-01', '2000-03-01', '2000-04-01',
                '2000-05-01', '2000-06-01', '2000-07-01', '2000-08-01'],
               dtype='datetime64[ns]', freq='MS'),
 a   -0.139387
 b   -0.668843
 c   -0.739266
 d    1.580636
 e   -0.288368
 dtype: float64,
                    A         B         C
 2000-01-01  0.852676  1.291526  0.000160
 2000-02-01 -0.890006 -1.078782 -1.325236
 2000-03-01 -0.816664  0.611592 -0.568064
 2000-04-01  0.385692 -0.066974 -0.652753
 2000-05-01  1.062071 -0.643894  1.496228
 2000-06-01  0.109572 -1.006114  0.825118
 2000-07-01  1.319482 -1.100164  2.183130
 2000-08-01  0.355768  0.165840  2.395885)

a   -0.868932
b    0.358298
c    0.515570
d    0.307473
e    1.289311
dtype: float64

In [17]:
long_series =pd.Series(np.random.randn(1000))
long_series

0      0.453714
1     -0.565112
2      0.642304
3     -0.348669
4      0.107717
         ...   
995   -0.218547
996    1.046709
997    0.027272
998    0.532506
999   -0.856837
Length: 1000, dtype: float64

In [18]:
df[:2]

A         B         C
2000-01-01  0.852676  1.291526  0.000160
2000-02-01 -0.890006 -1.078782 -1.325236

In [19]:
s.array

<NumpyExtensionArray>
[np.float64(-0.13938748641764048),   np.float64(-0.668842976347293),
   np.float64(-0.739265926125244),   np.float64(1.5806362689261864),
  np.float64(-0.2883675778519089)]
Length: 5, dtype: float64

In [22]:
df.columns = [x.lower() for x in df.columns]

In [23]:
df

a         b         c
2000-01-01  0.852676  1.291526  0.000160
2000-02-01 -0.890006 -1.078782 -1.325236
2000-03-01 -0.816664  0.611592 -0.568064
2000-04-01  0.385692 -0.066974 -0.652753
2000-05-01  1.062071 -0.643894  1.496228
2000-06-01  0.109572 -1.006114  0.825118
2000-07-01  1.319482 -1.100164  2.183130
2000-08-01  0.355768  0.165840  2.395885

In [26]:
s.to_numpy()

array([-0.13938749, -0.66884298, -0.73926593,  1.58063627, -0.28836758])

In [27]:
type(s.to_numpy())

numpy.ndarray

In [28]:
df.to_numpy()

array([[ 8.52676404e-01,  1.29152605e+00,  1.59850651e-04],
       [-8.90005581e-01, -1.07878220e+00, -1.32523634e+00],
       [-8.16664449e-01,  6.11592356e-01, -5.68064195e-01],
       [ 3.85691966e-01, -6.69743231e-02, -6.52753180e-01],
       [ 1.06207084e+00, -6.43893610e-01,  1.49622761e+00],
       [ 1.09572004e-01, -1.00611395e+00,  8.25117654e-01],
       [ 1.31948237e+00, -1.10016361e+00,  2.18312954e+00],
       [ 3.55768196e-01,  1.65839881e-01,  2.39588543e+00]])

In [34]:
df.values,type(df.values)

(array([[200,   4],
        [  2,   5],
        [  3,   6]]),
 numpy.ndarray)

In [61]:
df = pd.DataFrame({
    "one":pd.Series(np.random.randn(3),index=["a","b","c"]),
    "two":pd.Series(np.random.randn(4),index=["a","b","c","d"]), 
    "three":pd.Series(np.random.randn(3),index=["b","c","d"]), 
})
df

one       two     three
a  1.800093  0.145648       NaN
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [62]:
row = df.iloc[1]
row

one     -0.488320
two     -1.434606
three   -0.175069
Name: b, dtype: float64

In [63]:
column = df["two"]
column

a    0.145648
b   -1.434606
c   -0.112349
d    0.142161
Name: two, dtype: float64

In [64]:
df.sub(row,axis="columns")

one       two     three
a  2.288412  1.580254       NaN
b  0.000000  0.000000  0.000000
c  0.013382  1.322257  0.019159
d       NaN  1.576767 -0.138379

In [66]:
df.sub(row,axis=1)

one       two     three
a  2.288412  1.580254       NaN
b  0.000000  0.000000  0.000000
c  0.013382  1.322257  0.019159
d       NaN  1.576767 -0.138379

In [67]:
df.sub(column,axis="index")

one  two     three
a  1.654445  0.0       NaN
b  0.946286  0.0  1.259537
c -0.362589  0.0 -0.043561
d       NaN  0.0 -0.455609

In [68]:
dmi=df.copy()

In [69]:
dmi

one       two     three
a  1.800093  0.145648       NaN
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [71]:
dmi.index = pd.MultiIndex.from_tuples(
    [(1,"a"),(1,"b"),(1,"c"),(2,"a")],names=["first","second"]
)

In [72]:
dmi

one       two     three
first second                              
1     a       1.800093  0.145648       NaN
      b      -0.488320 -1.434606 -0.175069
      c      -0.474938 -0.112349 -0.155910
2     a            NaN  0.142161 -0.313448

In [73]:
s = pd.Series(np.arange(10))

In [74]:
divmod(s,3)

(0    0
 1    0
 2    0
 3    1
 4    1
 5    1
 6    2
 7    2
 8    2
 9    3
 dtype: int64,
 0    0
 1    1
 2    2
 3    0
 4    1
 5    2
 6    0
 7    1
 8    2
 9    0
 dtype: int64)

In [88]:
df2 = df.copy()
df2

one       two     three
a  1.800093  0.145648       NaN
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [90]:
df2.loc["a","three"] = 1.0

In [91]:
df2

one       two     three
a  1.800093  0.145648  1.000000
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [92]:
df+df2

one       two     three
a  3.600185  0.291296       NaN
b -0.976639 -2.869212 -0.350138
c -0.949875 -0.224698 -0.311819
d       NaN  0.284322 -0.626896

In [96]:
df.add(df2,fill_value=0.0)

one       two     three
a  3.600185  0.291296  1.000000
b -0.976639 -2.869212 -0.350138
c -0.949875 -0.224698 -0.311819
d       NaN  0.284322 -0.626896

In [112]:

df.loc["a","one"] = -0.01
df.empty,df.shape,df

(False,
 (4, 3),
         one       two     three
 a -0.010000  0.145648       NaN
 b -0.488320 -1.434606 -0.175069
 c -0.474938 -0.112349 -0.155910
 d       NaN  0.142161 -0.313448)

In [114]:
df.all(skipna=False)

one      True
two      True
three    True
dtype: bool

In [115]:
df

one       two     three
a -0.010000  0.145648       NaN
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [116]:
df.isna()

one    two  three
a  False  False   True
b  False  False  False
c  False  False  False
d   True  False  False

In [117]:
df.fillna(11)

one       two      three
a  -0.010000  0.145648  11.000000
b  -0.488320 -1.434606  -0.175069
c  -0.474938 -0.112349  -0.155910
d  11.000000  0.142161  -0.313448

In [118]:
df

one       two     three
a -0.010000  0.145648       NaN
b -0.488320 -1.434606 -0.175069
c -0.474938 -0.112349 -0.155910
d       NaN  0.142161 -0.313448

In [119]:
np.nan

nan

In [122]:
np.random.standard_normal((7,3))

array([[ 1.30738617, -2.24722319,  0.3741011 ],
       [ 0.01294739, -0.0666988 , -1.39625577],
       [ 0.87255686, -2.12305354,  2.62459527],
       [ 0.16700562,  0.82877265, -0.55475685],
       [ 1.2621675 ,  2.17118276,  0.58311519],
       [-0.49493013,  0.49041842, -1.04908272],
       [ 0.44192243, -1.35905471, -0.77579625]])

In [129]:
data = pd.DataFrame(np.arange(12).reshape(3,4),index=["oh","co","ne"],columns=["one","two","three","four"])
data

one  two  three  four
oh    0    1      2     3
co    4    5      6     7
ne    8    9     10    11

In [132]:
data.index = data.index.map(lambda x:x[:4].upper())

In [133]:
data

one  two  three  four
OH    0    1      2     3
CO    4    5      6     7
NE    8    9     10    11

In [135]:
ages = [20,22,25,27,21,23,37,31,61,45,41,32]
bins=[1,25,35,60,100]
age_ca = pd.cut(ages,bins)
age_ca

[(1, 25], (1, 25], (1, 25], (25, 35], (1, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(1, 25] < (25, 35] < (35, 60] < (60, 100]]

In [137]:
pd.Series(age_ca).value_counts()

(1, 25]      5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [142]:
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
A+B

array([[ 6,  8],
       [10, 12]])

In [143]:
np.dot(A,B)

array([[19, 22],
       [43, 50]])